services:
  backend:
    build:
      context: ./backend
    container_name: ${BACKEND_CONTAINER_NAME}
    expose:
      - "8080"
    networks:
      - effectivemobile-net
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/"]
      interval: 10s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:1.27.5-alpine
    container_name: ${NGINX_CONTAINER_NAME}
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - effectivemobile-net
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  effectivemobile-net:
    name: effectivemobile-net
